[Fix #6036] Make `Rails/BulkChangeTable` aware of string table name
Fixes #6036

Some ALTER methods accept not only symbols, but also strings as
table name. Since this cop assumes only symbols, an error will
occur if strings is received.

```
$ rubocop _0.57.2_ --only Rails/BulkChangeTable -d db/migrate/test.rb
Scanning /Users/watanabekazuma/workspace/ruby/rubocop/db/migrate/test.rb
An error occurred while Rails/BulkChangeTable cop was inspecting
/Users/watanabekazuma/workspace/ruby/rubocop/db/migrate/test.rb:6:2.
undefined method `value' for s(:str, "api_keys"):RuboCop::AST::StrNode
/Users/watanabekazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cop/rails/bulk_change_table.rb:235:in
`add_offense_for_alter_methods'
/Users/watanabekazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cop/rails/bulk_change_table.rb:150:in
`block in on_def'
/Users/watanabekazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cop/rails/bulk_change_table.rb:150:in
`each'
/Users/watanabekazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cop/rails/bulk_change_table.rb:150:in
`on_def'''''""'
```

In order to fix this bug, add `StrNode#value` method. In addition,
it fixes the false negative that occurred when using symbols and
strings as table names at the same time.