Support Ruby 3.1's anonymous block forwarding syntax
Follow up to https://github.com/whitequark/parser/pull/833.

Here is a traditional block forwarding.

```console
% ruby-parse -e 'def foo(&b) = bar(&b)'
warning: parser/current is loading parser/ruby31, which recognizes
warning: 3.1.0-dev-compliant syntax, but you are running 3.1.0.
warning: please see
https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(def :foo
  (args
    (blockarg :b))
  (send nil :bar
    (block-pass
      (lvar :b))))
```

The anonymous block argument introduced in Ruby 3.1, the value of `block-pass` is nil.
So `block-pass` will have the possibility of having nil.

```console
% ruby-parse -e 'def foo(&) = bar(&)'
warning: parser/current is loading parser/ruby31, which recognizes
warning: 3.1.0-dev-compliant syntax, but you are running 3.1.0.
warning: please see
https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(def :foo
  (args
    (blockarg nil))
  (send nil :bar
    (block-pass nil)))
```

This PR prevents the following error that occur when anonymous block forwarding is used:

```console
% ruby -rrubocop-ast -e 'include RuboCop::AST::Traversal; walk(RuboCop::AST::ProcessedSource.new("def foo(&) = bar(&)", 3.1).ast)'
/Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:131:in
`on_block_pass': undefined method `type' for nil:NilClass (NoMethodError)
        from /Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:159:in
        `block in on_send'
        from /Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:156:in
        `each'
        from /Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:156:in
        `each_with_index'
        from /Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:156:in
        `on_send'
        from /Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:154:in
        `on_def'
        from /Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:20:in
        `walk'
        from -e:1:in `<main>'
```